
export const FETCH_USER_INFO = "FETCH_USER_INFO";
export const FETCH_SESSION = "FETCH_SESSION";

export const FETCH_FACILITY_LIST = 'FETCH_FACILITY_LIST'
export const FETCH_FACILITY_INFO = 'FETCH_FACILITY_INFO'

export const FETCH_ANIMAL_LIST = 'FETCH_ANIMAL_LIST'
export const FETCH_ANIMAL_INFO = 'FETCH_ANIMAL_INFO'

export const FETCH_LIKED_ANIMAL_LIST = 'FETCH_LIKED_ANIMAL_LIST'

export const  FETCH_VOLUNTARY_LIST = ' FETCH_VOLUNTARY_LIST'