export const FETCH_USER_INFO = "FETCH_USER_INFO";
export const FETCH_SESSION = "FETCH_SESSION";

export const FETCH_FACILITY_LIST = 'FETCH_FACILITY_LIST'
export const FETCH_FACILITY_INFO = 'FETCH_FACILITY_INFO'

export const FETCH_ANIMAL_LIST = 'FETCH_ANIMAL_LIST'
export const FETCH_ANIMAL_INFO = 'FETCH_ANIMAL_INFO'
export const FETCH_ORDER_ANIMAL_LIST = 'FETCH_ORDER_ANIMAL_LIST'
export const FETCH_NUM_OF_ANIMALS = 'FETCH_NUM_OF_ANIMALS'

export const FETCH_LIKED_ANIMAL_LIST = 'FETCH_LIKED_ANIMAL_LIST'

export const  FETCH_VOLUNTARY_LIST = ' FETCH_VOLUNTARY_LIST'

export const FETCH_REPORT = 'FETCH_REPORT'
export const FETCH_REPORT_LIST = 'FETCH_REPORT_LIST'
export const FETCH_REPLY_LIST = 'FETCH_REPLY_LIST'

export const FETCH_VOLUNTARYBOARD_LIST = 'FETCH_VOLUNTARYBOARD_LIST'
export const FETCH_VOLUNTARYBOARD = 'FETCH_VOLUNTARYBOARD'
export const FETCH_VOL_COMMENT = 'FETCH_VOL_COMMENT'

export const  FETCH_MY_LIKED_ANIMAL_LIST = ' FETCH_MY_LIKED_ANIMAL_LIST'
export const  FETCH_MY_BOARD_LIST = ' FETCH_MY_BOARD_LIST'

export const FETCH_MEMBER_LIST = 'FETCH_MEMBER_LIST'

export const FETCH_ADMIN_MEMBER_LIST = 'FETCH_ADMIN_MEMBER_LIST'
export const FETCH_ADMIN_MEMBER = 'FETCH_ADMIN_MEMBER'

export const  FETCH_QNA_LIST = ' FETCH_QNA_LIST'
export const  FETCH_QNA = ' FETCH_QNA'
export const  FETCH_MY_QNA_LIST = ' FETCH_MY_QNA_LIST'

